name: discontinuous_range
description: For adding/subtracting sets of range of numbers, e.g. [ 1-3, 7-10 ]
version: 0.0.2
homepage: https://github.com/Schwusch/dart-discontinuous_range

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
